# Generated by Django 4.2.3 on 2023-07-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_publicaciones_creador_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='imagen',
            field=models.URLField(null=True),
        ),
    ]
