# Generated by Django 4.2.3 on 2023-07-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_admin',
        ),
    ]
